# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Pokemon.delete_all
RegionalPokedex.delete_all

pokemons = [
  {"regional_pokedex_id": 1, "regional_pokedex_no": 1, "national_pokedex_no": 810, "name": "サルノリ", "type": ["くさ"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 2, "national_pokedex_no": 811, "name": "バチンキー", "type": ["くさ"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 3, "national_pokedex_no": 812, "name": "ゴリランダー", "type": ["くさ"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 4, "national_pokedex_no": 813, "name": "ヒバニー", "type": ["ほのお"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 5, "national_pokedex_no": 814, "name": "ラビフット", "type": ["ほのお"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 6, "national_pokedex_no": 815, "name": "エースバーン", "type": ["ほのお"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 7, "national_pokedex_no": 816, "name": "メッソン", "type": ["みず"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 8, "national_pokedex_no": 817, "name": "ジメレオン", "type": ["みず"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 9, "national_pokedex_no": 818, "name": "インテレオン", "type": ["みず"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 10, "national_pokedex_no": 824, "name": "サッチムシ", "type": ["むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 11, "national_pokedex_no": 825, "name": "レドームシ", "type": ["むし", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 12, "national_pokedex_no": 826, "name": "イオルブ", "type": ["むし", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 13, "national_pokedex_no": 10, "name": "キャタピー", "type": ["むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 14, "national_pokedex_no": 11, "name": "トランセル", "type": ["むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 15, "national_pokedex_no": 12, "name": "バタフリー", "type": ["むし", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 16, "national_pokedex_no": 736, "name": "アゴジムシ", "type": ["むし", "でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 17, "national_pokedex_no": 737, "name": "デンヂムシ", "type": ["むし", "でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 18, "national_pokedex_no": 738, "name": "クワガノン", "type": ["むし", "でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 19, "national_pokedex_no": 163, "name": "ホーホー", "type": ["ノーマル", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 20, "national_pokedex_no": 164, "name": "ヨルノズク", "type": ["ノーマル", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 21, "national_pokedex_no": 821, "name": "ココガラ", "type": ["ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 22, "national_pokedex_no": 822, "name": "アオガラス", "type": ["ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 23, "national_pokedex_no": 823, "name": "アーマーガア", "type": ["ひこう", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 24, "national_pokedex_no": 819, "name": "ホシガリス", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 25, "national_pokedex_no": 820, "name": "ヨクバリス", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 26, "national_pokedex_no": 519, "name": "マメパト", "type": ["ノーマル", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 27, "national_pokedex_no": 520, "name": "ハトーボー", "type": ["ノーマル", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 28, "national_pokedex_no": 521, "name": "ケンホロウ", "type": ["ノーマル", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 29, "national_pokedex_no": 827, "name": "クスネ", "type": ["あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 30, "national_pokedex_no": 828, "name": "フォクスライ", "type": ["あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 31, "national_pokedex_no": 263, "name": "ジグザグマ", "type": ["あく", "ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 32, "national_pokedex_no": 264, "name": "マッスグマ", "type": ["あく", "ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 33, "national_pokedex_no": 862, "name": "タチフサグマ", "type": ["あく", "ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 34, "national_pokedex_no": 831, "name": "ウールー", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 35, "national_pokedex_no": 832, "name": "バイウールー", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 36, "national_pokedex_no": 270, "name": "ハスボー", "type": ["みず", "くさ"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 37, "national_pokedex_no": 271, "name": "ハスブレロ", "type": ["みず", "くさ"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 38, "national_pokedex_no": 272, "name": "ルンパッパ", "type": ["みず", "くさ"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 39, "national_pokedex_no": 273, "name": "タネボー", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 40, "national_pokedex_no": 274, "name": "コノハナ", "type": ["くさ", "あく"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 41, "national_pokedex_no": 275, "name": "ダーテング", "type": ["くさ", "あく"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 42, "national_pokedex_no": 833, "name": "カムカメ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 43, "national_pokedex_no": 834, "name": "カジリガメ", "type": ["みず", "いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 44, "national_pokedex_no": 509, "name": "チョロネコ", "type": ["あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 45, "national_pokedex_no": 510, "name": "レパルダス", "type": ["あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 46, "national_pokedex_no": 835, "name": "ワンパチ", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 47, "national_pokedex_no": 836, "name": "パルスワン", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 48, "national_pokedex_no": 659, "name": "ホルビー", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 49, "national_pokedex_no": 660, "name": "ホルード", "type": ["ノーマル", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 50, "national_pokedex_no": 572, "name": "チラーミィ", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 51, "national_pokedex_no": 573, "name": "チラチーノ", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 52, "national_pokedex_no": 761, "name": "アマカジ", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 53, "national_pokedex_no": 762, "name": "アママイコ", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 54, "national_pokedex_no": 763, "name": "アマージョ", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 55, "national_pokedex_no": 43, "name": "ナゾノクサ", "type": ["くさ", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 56, "national_pokedex_no": 44, "name": "クサイハナ", "type": ["くさ", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 57, "national_pokedex_no": 45, "name": "ラフレシア", "type": ["くさ", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 58, "national_pokedex_no": 182, "name": "キレイハナ", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 59, "national_pokedex_no": 406, "name": "スボミー", "type": ["くさ", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 60, "national_pokedex_no": 315, "name": "ロゼリア", "type": ["くさ", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 61, "national_pokedex_no": 407, "name": "ロズレイド", "type": ["くさ", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 62, "national_pokedex_no": 278, "name": "キャモメ", "type": ["みず", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 63, "national_pokedex_no": 279, "name": "ペリッパー", "type": ["みず", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 64, "national_pokedex_no": 595, "name": "バチュル", "type": ["むし", "でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 65, "national_pokedex_no": 596, "name": "デンチュラ", "type": ["むし", "でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 66, "national_pokedex_no": 309, "name": "ラクライ", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 67, "national_pokedex_no": 310, "name": "ライボルト", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 68, "national_pokedex_no": 37, "name": "ロコン", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 69, "national_pokedex_no": 38, "name": "キュウコン", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 70, "national_pokedex_no": 58, "name": "ガーディ", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 71, "national_pokedex_no": 59, "name": "ウインディ", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 72, "national_pokedex_no": 582, "name": "バニプッチ", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 73, "national_pokedex_no": 583, "name": "バニリッチ", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 74, "national_pokedex_no": 584, "name": "バイバニラ", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 75, "national_pokedex_no": 220, "name": "ウリムー", "type": ["こおり", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 76, "national_pokedex_no": 221, "name": "イノムー", "type": ["こおり", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 77, "national_pokedex_no": 473, "name": "マンムー", "type": ["こおり", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 78, "national_pokedex_no": 225, "name": "デリバード", "type": ["こおり", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 79, "national_pokedex_no": 361, "name": "ユキワラシ", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 80, "national_pokedex_no": 362, "name": "オニゴーリ", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 81, "national_pokedex_no": 478, "name": "ユキメノコ", "type": ["こおり", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 82, "national_pokedex_no": 343, "name": "ヤジロン", "type": ["じめん", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 83, "national_pokedex_no": 344, "name": "ネンドール", "type": ["じめん", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 84, "national_pokedex_no": 749, "name": "ドロバンコ", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 85, "national_pokedex_no": 750, "name": "バンバドロ", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 86, "national_pokedex_no": 557, "name": "イシズマイ", "type": ["むし", "いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 87, "national_pokedex_no": 558, "name": "イワパレス", "type": ["むし", "いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 88, "national_pokedex_no": 622, "name": "ゴビット", "type": ["じめん", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 89, "national_pokedex_no": 623, "name": "ゴルーグ", "type": ["じめん", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 90, "national_pokedex_no": 517, "name": "ムンナ", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 91, "national_pokedex_no": 518, "name": "ムシャーナ", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 92, "national_pokedex_no": 177, "name": "ネイティ", "type": ["エスパー", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 93, "national_pokedex_no": 178, "name": "ネイティオ", "type": ["エスパー", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 94, "national_pokedex_no": 759, "name": "ヌイコグマ", "type": ["ノーマル", "かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 95, "national_pokedex_no": 760, "name": "キテルグマ", "type": ["ノーマル", "かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 96, "national_pokedex_no": 459, "name": "ユキカブリ", "type": ["くさ", "こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 97, "national_pokedex_no": 460, "name": "ユキノオー", "type": ["くさ", "こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 98, "national_pokedex_no": 98, "name": "クラブ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 99, "national_pokedex_no": 99, "name": "キングラー", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 100, "national_pokedex_no": 194, "name": "ウパー", "type": ["みず", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 101, "national_pokedex_no": 195, "name": "ヌオー", "type": ["みず", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 102, "national_pokedex_no": 341, "name": "ヘイガニ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 103, "national_pokedex_no": 342, "name": "シザリガー", "type": ["みず", "あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 104, "national_pokedex_no": 290, "name": "ツチニン", "type": ["むし", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 105, "national_pokedex_no": 291, "name": "テッカニン", "type": ["むし", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 106, "national_pokedex_no": 292, "name": "ヌケニン", "type": ["むし", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 107, "national_pokedex_no": 236, "name": "バルキー", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 108, "national_pokedex_no": 106, "name": "サワムラー", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 109, "national_pokedex_no": 107, "name": "エビワラー", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 110, "national_pokedex_no": 237, "name": "カポエラー", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 111, "national_pokedex_no": 674, "name": "ヤンチャム", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 112, "national_pokedex_no": 675, "name": "ゴロンダ", "type": ["かくとう", "あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 113, "national_pokedex_no": 599, "name": "ギアル", "type": ["はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 114, "national_pokedex_no": 600, "name": "ギギアル", "type": ["はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 115, "national_pokedex_no": 601, "name": "ギギギアル", "type": ["はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 116, "national_pokedex_no": 415, "name": "ミツハニー", "type": ["むし", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 117, "national_pokedex_no": 416, "name": "ビークイン", "type": ["むし", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 118, "national_pokedex_no": 436, "name": "ドーミラー", "type": ["はがね", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 119, "national_pokedex_no": 437, "name": "ドータクン", "type": ["はがね", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 120, "national_pokedex_no": 280, "name": "ラルトス", "type": ["エスパー", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 121, "national_pokedex_no": 281, "name": "キルリア", "type": ["エスパー", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 122, "national_pokedex_no": 282, "name": "サーナイト", "type": ["エスパー", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 123, "national_pokedex_no": 475, "name": "エルレイド", "type": ["エスパー", "かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 124, "national_pokedex_no": 425, "name": "フワンテ", "type": ["ゴースト", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 125, "national_pokedex_no": 426, "name": "フワライド", "type": ["ゴースト", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 126, "national_pokedex_no": 829, "name": "ヒメンカ", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 127, "national_pokedex_no": 830, "name": "ワタシラガ", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 128, "national_pokedex_no": 420, "name": "チェリンボ", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 129, "national_pokedex_no": 421, "name": "チェリム", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 130, "national_pokedex_no": 434, "name": "スカンプー", "type": ["どく", "あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 131, "national_pokedex_no": 435, "name": "スカタンク", "type": ["どく", "あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 132, "national_pokedex_no": 535, "name": "オタマロ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 133, "national_pokedex_no": 536, "name": "ガマガル", "type": ["みず", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 134, "national_pokedex_no": 537, "name": "ガマゲロゲ", "type": ["みず", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 135, "national_pokedex_no": 355, "name": "ヨマワル", "type": ["ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 136, "national_pokedex_no": 356, "name": "サマヨール", "type": ["ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 137, "national_pokedex_no": 477, "name": "ヨノワール", "type": ["ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 138, "national_pokedex_no": 66, "name": "ワンリキー", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 139, "national_pokedex_no": 67, "name": "ゴーリキー", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 140, "national_pokedex_no": 68, "name": "カイリキー", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 141, "national_pokedex_no": 92, "name": "ゴース", "type": ["ゴースト", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 142, "national_pokedex_no": 93, "name": "ゴースト", "type": ["ゴースト", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 143, "national_pokedex_no": 94, "name": "ゲンガー", "type": ["ゴースト", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 144, "national_pokedex_no": 129, "name": "コイキング", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 145, "national_pokedex_no": 130, "name": "ギャラドス", "type": ["みず", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 146, "national_pokedex_no": 118, "name": "トサキント", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 147, "national_pokedex_no": 119, "name": "アズマオウ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 148, "national_pokedex_no": 223, "name": "テッポウオ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 149, "national_pokedex_no": 224, "name": "オクタン", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 150, "national_pokedex_no": 90, "name": "シェルダー", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 151, "national_pokedex_no": 91, "name": "パルシェン", "type": ["みず", "こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 152, "national_pokedex_no": 349, "name": "ヒンバス", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 153, "national_pokedex_no": 350, "name": "ミロカロス", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 154, "national_pokedex_no": 550, "name": "バスラオ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 155, "national_pokedex_no": 746, "name": "ヨワシ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 156, "national_pokedex_no": 771, "name": "ナマコブシ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 157, "national_pokedex_no": 568, "name": "ヤブクロン", "type": ["どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 158, "national_pokedex_no": 569, "name": "ダストダス", "type": ["どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 159, "national_pokedex_no": 850, "name": "ヤクデ", "type": ["ほのお", "むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 160, "national_pokedex_no": 851, "name": "マルヤクデ", "type": ["ほのお", "むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 161, "national_pokedex_no": 837, "name": "タンドン", "type": ["いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 162, "national_pokedex_no": 838, "name": "トロッゴン", "type": ["いわ", "ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 163, "national_pokedex_no": 839, "name": "セキタンザン", "type": ["いわ", "ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 164, "national_pokedex_no": 50, "name": "ディグダ", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 165, "national_pokedex_no": 51, "name": "ダグトリオ", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 166, "national_pokedex_no": 529, "name": "モグリュー", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 167, "national_pokedex_no": 530, "name": "ドリュウズ", "type": ["じめん", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 168, "national_pokedex_no": 524, "name": "ダンゴロ", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 169, "national_pokedex_no": 525, "name": "ガントル", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 170, "national_pokedex_no": 526, "name": "ギガイアス", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 171, "national_pokedex_no": 532, "name": "ドッコラー", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 172, "national_pokedex_no": 533, "name": "ドテッコツ", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 173, "national_pokedex_no": 534, "name": "ローブシン", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 174, "national_pokedex_no": 527, "name": "コロモリ", "type": ["エスパー", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 175, "national_pokedex_no": 528, "name": "ココロモリ", "type": ["エスパー", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 176, "national_pokedex_no": 714, "name": "オンバット", "type": ["ひこう", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 177, "national_pokedex_no": 715, "name": "オンバーン", "type": ["ひこう", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 178, "national_pokedex_no": 95, "name": "イワーク", "type": ["いわ", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 179, "national_pokedex_no": 208, "name": "ハガネール", "type": ["はがね", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 180, "national_pokedex_no": 846, "name": "サシカマス", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 181, "national_pokedex_no": 847, "name": "カマスジョー", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 182, "national_pokedex_no": 52, "name": "ニャース", "type": ["はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 183, "national_pokedex_no": 863, "name": "ニャイキング", "type": ["はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 184, "national_pokedex_no": 53, "name": "ペルシアン", "type": ["ノーマル"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 185, "national_pokedex_no": 868, "name": "マホミル", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 186, "national_pokedex_no": 869, "name": "マホイップ", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 187, "national_pokedex_no": 742, "name": "アブリー", "type": ["むし", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 188, "national_pokedex_no": 743, "name": "アブリボン", "type": ["むし", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 189, "national_pokedex_no": 597, "name": "テッシード", "type": ["くさ", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 190, "national_pokedex_no": 598, "name": "ナットレイ", "type": ["くさ", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 191, "national_pokedex_no": 710, "name": "バケッチャ", "type": ["ゴースト", "くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 192, "national_pokedex_no": 711, "name": "パンプジン", "type": ["ゴースト", "くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 193, "national_pokedex_no": 172, "name": "ピチュー", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 194, "national_pokedex_no": 25, "name": "ピカチュウ", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 195, "national_pokedex_no": 26, "name": "ライチュウ", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 196, "national_pokedex_no": 133, "name": "イーブイ", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 197, "national_pokedex_no": 134, "name": "シャワーズ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 198, "national_pokedex_no": 135, "name": "サンダース", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 199, "national_pokedex_no": 136, "name": "ブースター", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 200, "national_pokedex_no": 196, "name": "エーフィ", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 201, "national_pokedex_no": 197, "name": "ブラッキー", "type": ["あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 202, "national_pokedex_no": 470, "name": "リーフィア", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 203, "national_pokedex_no": 471, "name": "グレイシア", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 204, "national_pokedex_no": 700, "name": "ニンフィア", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 205, "national_pokedex_no": 840, "name": "カジッチュ", "type": ["くさ", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 206, "national_pokedex_no": 841, "name": "アップリュー", "type": ["くさ", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 207, "national_pokedex_no": 842, "name": "タルップル", "type": ["くさ", "ドラゴン"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 208, "national_pokedex_no": 677, "name": "ニャスパー", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 209, "national_pokedex_no": 678, "name": "ニャオニクス", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 210, "national_pokedex_no": 684, "name": "ペロッパフ", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 211, "national_pokedex_no": 685, "name": "ペロリーム", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 212, "national_pokedex_no": 682, "name": "シュシュプ", "type": ["フェアリー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 213, "national_pokedex_no": 683, "name": "フレフワン", "type": ["フェアリー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 214, "national_pokedex_no": 751, "name": "シズクモ", "type": ["みず", "むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 215, "national_pokedex_no": 752, "name": "オニシズクモ", "type": ["みず", "むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 216, "national_pokedex_no": 360, "name": "ソーナノ", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 217, "national_pokedex_no": 202, "name": "ソーナンス", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 218, "national_pokedex_no": 83, "name": "カモネギ", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 219, "national_pokedex_no": 865, "name": "ネギガナイト", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 220, "national_pokedex_no": 170, "name": "チョンチー", "type": ["みず", "でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 221, "national_pokedex_no": 171, "name": "ランターン", "type": ["みず", "でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 222, "national_pokedex_no": 453, "name": "グレッグル", "type": ["どく", "かくとう"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 223, "national_pokedex_no": 454, "name": "ドクロッグ", "type": ["どく", "かくとう"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 224, "national_pokedex_no": 559, "name": "ズルッグ", "type": ["あく", "かくとう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 225, "national_pokedex_no": 560, "name": "ズルズキン", "type": ["あく", "かくとう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 226, "national_pokedex_no": 618, "name": "マッギョ", "type": ["じめん", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 227, "national_pokedex_no": 213, "name": "ツボツボ", "type": ["むし", "いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 228, "national_pokedex_no": 339, "name": "ドジョッチ", "type": ["みず", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 229, "national_pokedex_no": 340, "name": "ナマズン", "type": ["みず", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 230, "national_pokedex_no": 422, "name": "カラナクシ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 231, "national_pokedex_no": 423, "name": "トリトドン", "type": ["みず", "じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 232, "national_pokedex_no": 767, "name": "コソクムシ", "type": ["むし", "みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 233, "national_pokedex_no": 768, "name": "グソクムシャ", "type": ["むし", "みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 234, "national_pokedex_no": 688, "name": "カメテテ", "type": ["いわ", "みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 235, "national_pokedex_no": 689, "name": "ガメノデス", "type": ["いわ", "みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 236, "national_pokedex_no": 222, "name": "サニーゴ", "type": ["ゴースト"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 237, "national_pokedex_no": 864, "name": "サニゴーン", "type": ["ゴースト"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 238, "national_pokedex_no": 859, "name": "ベロバー", "type": ["あく", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 239, "national_pokedex_no": 860, "name": "ギモー", "type": ["あく", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 240, "national_pokedex_no": 861, "name": "オーロンゲ", "type": ["あく", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 241, "national_pokedex_no": 856, "name": "ミブリム", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 242, "national_pokedex_no": 857, "name": "テブリム", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 243, "national_pokedex_no": 858, "name": "ブリムオン", "type": ["エスパー", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 244, "national_pokedex_no": 757, "name": "ヤトウモリ", "type": ["どく", "ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 245, "national_pokedex_no": 758, "name": "エンニュート", "type": ["どく", "ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 246, "national_pokedex_no": 624, "name": "コマタナ", "type": ["あく", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 247, "national_pokedex_no": 625, "name": "キリキザン", "type": ["あく", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 248, "national_pokedex_no": 538, "name": "ナゲキ", "type": ["かくとう"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 249, "national_pokedex_no": 539, "name": "ダゲキ", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 250, "national_pokedex_no": 109, "name": "ドガース", "type": ["どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 251, "national_pokedex_no": 110, "name": "マタドガス", "type": ["どく", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 252, "national_pokedex_no": 438, "name": "ウソハチ", "type": ["いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 253, "national_pokedex_no": 185, "name": "ウソッキー", "type": ["いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 254, "national_pokedex_no": 173, "name": "ピィ", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 255, "national_pokedex_no": 35, "name": "ピッピ", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 256, "national_pokedex_no": 36, "name": "ピクシー", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 257, "national_pokedex_no": 175, "name": "トゲピー", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 258, "national_pokedex_no": 176, "name": "トゲチック", "type": ["フェアリー", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 259, "national_pokedex_no": 468, "name": "トゲキッス", "type": ["フェアリー", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 260, "national_pokedex_no": 446, "name": "ゴンベ", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 261, "national_pokedex_no": 143, "name": "カビゴン", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 262, "national_pokedex_no": 546, "name": "モンメン", "type": ["くさ", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 263, "national_pokedex_no": 547, "name": "エルフーン", "type": ["くさ", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 264, "national_pokedex_no": 111, "name": "サイホーン", "type": ["じめん", "いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 265, "national_pokedex_no": 112, "name": "サイドン", "type": ["じめん", "いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 266, "national_pokedex_no": 464, "name": "ドサイドン", "type": ["じめん", "いわ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 267, "national_pokedex_no": 574, "name": "ゴチム", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 268, "national_pokedex_no": 575, "name": "ゴチミル", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 269, "national_pokedex_no": 576, "name": "ゴチルゼル", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 270, "national_pokedex_no": 577, "name": "ユニラン", "type": ["エスパー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 271, "national_pokedex_no": 578, "name": "ダブラン", "type": ["エスパー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 272, "national_pokedex_no": 579, "name": "ランクルス", "type": ["エスパー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 273, "national_pokedex_no": 588, "name": "カブルモ", "type": ["むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 274, "national_pokedex_no": 589, "name": "シュバルゴ", "type": ["むし", "はがね"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 275, "national_pokedex_no": 616, "name": "チョボマキ", "type": ["むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 276, "national_pokedex_no": 617, "name": "アギルダー", "type": ["むし"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 277, "national_pokedex_no": 605, "name": "リグレー", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 278, "national_pokedex_no": 606, "name": "オーベム", "type": ["エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 279, "national_pokedex_no": 613, "name": "クマシュン", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 280, "national_pokedex_no": 614, "name": "ツンベアー", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 281, "national_pokedex_no": 627, "name": "ワシボン", "type": ["ノーマル", "ひこう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 282, "national_pokedex_no": 628, "name": "ウォーグル", "type": ["ノーマル", "ひこう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 283, "national_pokedex_no": 629, "name": "バルチャイ", "type": ["あく", "ひこう"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 284, "national_pokedex_no": 630, "name": "バルジーナ", "type": ["あく", "ひこう"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 285, "national_pokedex_no": 451, "name": "スコルピ", "type": ["どく", "むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 286, "national_pokedex_no": 452, "name": "ドラピオン", "type": ["どく", "あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 287, "national_pokedex_no": 607, "name": "ヒトモシ", "type": ["ゴースト", "ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 288, "national_pokedex_no": 608, "name": "ランプラー", "type": ["ゴースト", "ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 289, "national_pokedex_no": 609, "name": "シャンデラ", "type": ["ゴースト", "ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 290, "national_pokedex_no": 686, "name": "マーイーカ", "type": ["あく", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 291, "national_pokedex_no": 687, "name": "カラマネロ", "type": ["あく", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 292, "national_pokedex_no": 215, "name": "ニューラ", "type": ["あく", "こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 293, "national_pokedex_no": 461, "name": "マニューラ", "type": ["あく", "こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 294, "national_pokedex_no": 302, "name": "ヤミラミ", "type": ["あく", "ゴースト"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 295, "national_pokedex_no": 303, "name": "クチート", "type": ["はがね", "フェアリー"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 296, "national_pokedex_no": 556, "name": "マラカッチ", "type": ["くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 297, "national_pokedex_no": 561, "name": "シンボラー", "type": ["エスパー", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 298, "national_pokedex_no": 447, "name": "リオル", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 299, "national_pokedex_no": 448, "name": "ルカリオ", "type": ["かくとう", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 300, "national_pokedex_no": 324, "name": "コータス", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 301, "national_pokedex_no": 778, "name": "ミミッキュ", "type": ["ゴースト", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 302, "national_pokedex_no": 878, "name": "ゾウドウ", "type": ["はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 303, "national_pokedex_no": 879, "name": "ダイオウドウ", "type": ["はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 304, "national_pokedex_no": 211, "name": "ハリーセン", "type": ["みず", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 305, "national_pokedex_no": 592, "name": "プルリル", "type": ["みず", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 306, "national_pokedex_no": 593, "name": "ブルンゲル", "type": ["みず", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 307, "national_pokedex_no": 747, "name": "ヒドイデ", "type": ["どく", "みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 308, "national_pokedex_no": 748, "name": "ドヒドイデ", "type": ["どく", "みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 309, "national_pokedex_no": 845, "name": "ウッウ", "type": ["ひこう", "みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 310, "national_pokedex_no": 848, "name": "エレズン", "type": ["でんき", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 311, "national_pokedex_no": 849, "name": "ストリンダー", "type": ["でんき", "どく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 312, "national_pokedex_no": 843, "name": "スナヘビ", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 313, "national_pokedex_no": 844, "name": "サダイジャ", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 314, "national_pokedex_no": 449, "name": "ヒポポタス", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 315, "national_pokedex_no": 450, "name": "カバルドン", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 316, "national_pokedex_no": 632, "name": "アイアント", "type": ["むし", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 317, "national_pokedex_no": 631, "name": "クイタラン", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 318, "national_pokedex_no": 694, "name": "エリキテル", "type": ["でんき", "ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 319, "national_pokedex_no": 695, "name": "エレザード", "type": ["でんき", "ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 320, "national_pokedex_no": 701, "name": "ルチャブル", "type": ["かくとう", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 321, "national_pokedex_no": 328, "name": "ナックラー", "type": ["じめん"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 322, "national_pokedex_no": 329, "name": "ビブラーバ", "type": ["じめん", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 323, "national_pokedex_no": 330, "name": "フライゴン", "type": ["じめん", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 324, "national_pokedex_no": 610, "name": "キバゴ", "type": ["ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 325, "national_pokedex_no": 611, "name": "オノンド", "type": ["ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 326, "national_pokedex_no": 612, "name": "オノノクス", "type": ["ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 327, "national_pokedex_no": 562, "name": "デスマス", "type": ["じめん", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 328, "national_pokedex_no": 867, "name": "デスバーン", "type": ["じめん", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 329, "national_pokedex_no": 563, "name": "デスカーン", "type": ["ゴースト"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 330, "national_pokedex_no": 679, "name": "ヒトツキ", "type": ["はがね", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 331, "national_pokedex_no": 680, "name": "ニダンギル", "type": ["はがね", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 332, "national_pokedex_no": 681, "name": "ギルガルド", "type": ["はがね", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 333, "national_pokedex_no": 77, "name": "ポニータ", "type": ["エスパー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 334, "national_pokedex_no": 78, "name": "ギャロップ", "type": ["エスパー", "フェアリー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 335, "national_pokedex_no": 854, "name": "ヤバチャ", "type": ["ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 336, "national_pokedex_no": 855, "name": "ポットデス", "type": ["ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 337, "national_pokedex_no": 876, "name": "イエッサン", "type": ["エスパー", "ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 338, "national_pokedex_no": 708, "name": "ボクレー", "type": ["ゴースト", "くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 339, "national_pokedex_no": 709, "name": "オーロット", "type": ["ゴースト", "くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 340, "national_pokedex_no": 755, "name": "ネマシュ", "type": ["くさ", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 341, "national_pokedex_no": 756, "name": "マシェード", "type": ["くさ", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 342, "national_pokedex_no": 765, "name": "ヤレユータン", "type": ["ノーマル", "エスパー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 343, "national_pokedex_no": 766, "name": "ナゲツケサル", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 344, "national_pokedex_no": 877, "name": "モルペコ", "type": ["でんき", "あく"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 345, "national_pokedex_no": 870, "name": "タイレーツ", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 346, "national_pokedex_no": 780, "name": "ジジーロン", "type": ["ノーマル", "ドラゴン"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 347, "national_pokedex_no": 776, "name": "バクガメス", "type": ["ほのお", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 348, "national_pokedex_no": 777, "name": "トゲデマル", "type": ["でんき", "はがね"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 349, "national_pokedex_no": 872, "name": "ユキハミ", "type": ["こおり", "むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 350, "national_pokedex_no": 873, "name": "モスノウ", "type": ["こおり", "むし"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 351, "national_pokedex_no": 852, "name": "タタッコ", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 352, "national_pokedex_no": 853, "name": "オトスパス", "type": ["かくとう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 353, "national_pokedex_no": 871, "name": "バチンウニ", "type": ["でんき"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 354, "national_pokedex_no": 458, "name": "タマンタ", "type": ["みず", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 355, "national_pokedex_no": 226, "name": "マンタイン", "type": ["みず", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 356, "national_pokedex_no": 320, "name": "ホエルコ", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 357, "national_pokedex_no": 321, "name": "ホエルオー", "type": ["みず"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 358, "national_pokedex_no": 712, "name": "カチコール", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 359, "national_pokedex_no": 713, "name": "クレベース", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 360, "national_pokedex_no": 781, "name": "ダダリン", "type": ["ゴースト", "くさ"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 361, "national_pokedex_no": 131, "name": "ラプラス", "type": ["みず", "こおり"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 362, "national_pokedex_no": 337, "name": "ルナトーン", "type": ["いわ", "エスパー"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 363, "national_pokedex_no": 338, "name": "ソルロック", "type": ["いわ", "エスパー"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 364, "national_pokedex_no": 439, "name": "マネネ", "type": ["エスパー", "フェアリー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 365, "national_pokedex_no": 122, "name": "バリヤード", "type": ["こおり", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 366, "national_pokedex_no": 866, "name": "バリコオル", "type": ["こおり", "エスパー"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 367, "national_pokedex_no": 554, "name": "ダルマッカ", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 368, "national_pokedex_no": 555, "name": "ヒヒダルマ", "type": ["こおり"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 369, "national_pokedex_no": 874, "name": "イシヘンジン", "type": ["いわ"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 370, "national_pokedex_no": 875, "name": "コオリッポ", "type": ["こおり"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 371, "national_pokedex_no": 884, "name": "ジュラルドン", "type": ["はがね", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 372, "national_pokedex_no": 479, "name": "ロトム", "type": ["でんき", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 373, "national_pokedex_no": 132, "name": "メタモン", "type": ["ノーマル"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 374, "national_pokedex_no": 880, "name": "パッチラゴン", "type": ["でんき", "ドラゴン"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 375, "national_pokedex_no": 881, "name": "パッチルドン", "type": ["でんき", "こおり"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 376, "national_pokedex_no": 882, "name": "ウオノラゴン", "type": ["みず", "ドラゴン"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 377, "national_pokedex_no": 883, "name": "ウオチルドン", "type": ["みず", "こおり"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 378, "national_pokedex_no": 4, "name": "ヒトカゲ", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 379, "national_pokedex_no": 5, "name": "リザード", "type": ["ほのお"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 380, "national_pokedex_no": 6, "name": "リザードン", "type": ["ほのお", "ひこう"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 381, "national_pokedex_no": 772, "name": "タイプ:ヌル", "type": ["ノーマル"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 382, "national_pokedex_no": 773, "name": "シルヴァディ", "type": ["ノーマル"], "appear_on_sword": false, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 383, "national_pokedex_no": 246, "name": "ヨーギラス", "type": ["いわ", "じめん"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 384, "national_pokedex_no": 247, "name": "サナギラス", "type": ["いわ", "じめん"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 385, "national_pokedex_no": 248, "name": "バンギラス", "type": ["いわ", "あく"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 386, "national_pokedex_no": 633, "name": "モノズ", "type": ["あく", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 387, "national_pokedex_no": 634, "name": "ジヘッド", "type": ["あく", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 388, "national_pokedex_no": 635, "name": "サザンドラ", "type": ["あく", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 389, "national_pokedex_no": 704, "name": "ヌメラ", "type": ["ドラゴン"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 390, "national_pokedex_no": 705, "name": "ヌメイル", "type": ["ドラゴン"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 391, "national_pokedex_no": 706, "name": "ヌメルゴン", "type": ["ドラゴン"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 392, "national_pokedex_no": 782, "name": "ジャラコ", "type": ["ドラゴン"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 393, "national_pokedex_no": 783, "name": "ジャランゴ", "type": ["ドラゴン", "かくとう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 394, "national_pokedex_no": 784, "name": "ジャラランガ", "type": ["ドラゴン", "かくとう"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 395, "national_pokedex_no": 885, "name": "ドラメシヤ", "type": ["ドラゴン", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 396, "national_pokedex_no": 886, "name": "ドロンチ", "type": ["ドラゴン", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 397, "national_pokedex_no": 887, "name": "ドラパルト", "type": ["ドラゴン", "ゴースト"], "appear_on_sword": true, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 398, "national_pokedex_no": 888, "name": "ザシアン", "type": ["フェアリー"], "appear_on_sword": true, "appear_on_shield": false},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 399, "national_pokedex_no": 889, "name": "ザマゼンタ", "type": ["かくとう"], "appear_on_sword": false, "appear_on_shield": true},
  {"regional_pokedex_id": 1, "regional_pokedex_no": 400, "national_pokedex_no": 890, "name": "ムゲンダイナ", "type": ["どく", "ドラゴン"], "appear_on_sword": true, "appear_on_shield": true},
]

RegionalPokedex.create(
  id: 1,
  name: 'galar',
  display_name: 'ガラル'
)

pokemons.each do |pokemon|
  type1, type2 = pokemon[:type]
  Pokemon.create(
    regional_pokedex_id: pokemon[:regional_pokedex_id],
    name: pokemon[:name],
    type1: type1,
    type2: type2,
    national_pokedex_no: pokemon[:national_pokedex_no],
    regional_pokedex_no: pokemon[:regional_pokedex_no],
    appear_on_sword: pokemon[:appear_on_sword],
    appear_on_shield: pokemon[:appear_on_shield]
  )
end

